badge = "r"
artifact_url = "https://github.com/jnsiemer/scalable_rbe_prototype"
cd = "c"
citation = "@misc{SP:KLSS26,\n  author = {Michael Klooß and Russell W. F. Lai and Jan Niklas Siemer and Monisha Swarnakar},\n  title = {{Scalable Registration-Based Encryption from Lattices}},\n  year = {2026},\n}"
license_url = "https://www.mozilla.org/en-US/MPL/2.0/"
infrastructure_constraints = "It can be executed on any computer. Choosing a typical end-user device is a representative choice."
infrastructure_access = ""
install_script = "https://github.com/jnsiemer/scalable_rbe_prototype/blob/main/Dockerfile"
use = "The provided implementation is a prototype and should not be used in a production environment. It is meant to showcase the performance of our algorithms and does not provide any side-channel security."
destructive = "None. If a test or benchmark should start to fail, this will be due to an interrupted execution of a test or benchmark. All functions work on a locally centralised database in the directory registry_db, which holds the registry of the RBE. Every test and benchmark wipes it at the end of its execution and some tests require an empty database. So, please delete the registry_db directory if it exists and you are not running any tests or benchmarks."
claim1 = "Our code is available via GitHub: https://github.com/jnsiemer/scalable_rbe_prototype and Rust's library manager crates.io: https://crates.io/crates/scalable-rb and Zenodo: https://doi.org/10.5281/zenodo.19004915"
script1 = "https://doi.org/10.5281/zenodo.19004915"
expected1 = "If you can access the provided link or clone the git repository (recommended)."
hw = ">5 GB free disk space and >8 GB RAM available"
sw = ""
api = ""
gui = "n"
readme = "https://github.com/jnsiemer/scalable_rbe_prototype/blob/main/README.md"
claim2 = "Our code is functional."
script2 = "https://github.com/jnsiemer/scalable_rbe_prototype/blob/main/src/rbe.rs#L800"
expected2 = "If you can run cargo test --release rbe::test::full_length_id and the test finishes successfully. This test initialises a new RBE, registers a new identity, encrypts and decrypts w.r.t. this identity and checks whether the output matches the input message, i.e. it shows correctness of the construction. The documentation is available at https://docs.rs/scalable-rbe. Completeness and Exercisability can be inspected in the GitHub repository."
claim3 = "Our results are reproducable, i.e. the claims from Table 3 in our paper for our construction are reproducable."
script3 = "https://github.com/jnsiemer/scalable_rbe_prototype/blob/main/Makefile"
expected3 = "If the reported execution times are representative w.r.t. the setup (considering differences in CPU, RAM, OS, AVX2 availability, local settings, etc.) or similar to the reported ones. The benchmarks can be run using cargo bench RBE"
